#!/usr/bin/env bash
# appset-matrix.sh - emit a JSON array describing every (app x cluster) Argo CD
# Application generated by bootstrap/appset-apps.yaml, for use as a GitHub Actions
# matrix (`fromJSON`). The appset is the single source of truth: this script
# self-discovers apps, clusters, tags, the charts repo, and the chart/values
# paths, so the workflows never hardcode any of them (and need no cookiecutter
# variables - they are copied verbatim via _copy_without_render).
#
# TEMPLATE ASSUMPTION: this is a deliberately narrow helper that reads this repo's
# simple list generator (.spec.generators[0].list.elements). It is NOT a generic
# ApplicationSet parser. If you switch appset-apps.yaml to a Git/files/cluster/
# matrix generator, update this script. See docs/tutorial-simplifications.md.
#
# Usage: appset-matrix.sh [path-to-appset-apps.yaml]
# Output (stdout): a single compact JSON array, one object per element:
#   {appName,cluster,environment,releaseName,targetRevision,
#    chartRepo,chartPath,valuesFile,namespace,pinned}
# "pinned" is true when targetRevision is a release tag <app>-<semver>
# (stage/prod) and false for a moving branch like 'main' (dev).
set -euo pipefail

APPSET="${1:-bootstrap/appset-apps.yaml}"

command -v yq >/dev/null || { echo "appset-matrix: yq (mikefarah) not found" >&2; exit 1; }
command -v jq >/dev/null || { echo "appset-matrix: jq not found" >&2; exit 1; }
[ -f "$APPSET" ] || { echo "appset-matrix: $APPSET not found" >&2; exit 1; }

# The chart source is the template source that has a 'path' (the values source
# uses 'ref: values' and has no 'path').
chart_repo=$(yq '.spec.template.spec.sources[] | select(has("path")) | .repoURL' "$APPSET")
chart_path_tmpl=$(yq '.spec.template.spec.sources[] | select(has("path")) | .path' "$APPSET")
# "charts/{{.appName}}" -> prefix "charts/" (drop the Argo go-template placeholder)
chart_prefix=${chart_path_tmpl%%\{\{*}

# Destination namespace template, e.g. "{{.environment}}-targetns" -> "-targetns"
ns_tmpl=$(yq '.spec.template.spec.destination.namespace' "$APPSET")
ns_suffix=${ns_tmpl#*\}\}}

n=$(yq '.spec.generators[0].list.elements | length' "$APPSET")

emit() {
  local i="$1"
  local appName cluster environment releaseName targetRevision pinned
  appName=$(yq ".spec.generators[0].list.elements[$i].appName" "$APPSET")
  cluster=$(yq ".spec.generators[0].list.elements[$i].cluster" "$APPSET")
  environment=$(yq ".spec.generators[0].list.elements[$i].environment" "$APPSET")
  releaseName=$(yq ".spec.generators[0].list.elements[$i].releaseName" "$APPSET")
  targetRevision=$(yq ".spec.generators[0].list.elements[$i].targetRevision" "$APPSET")

  if printf '%s' "$targetRevision" | grep -Eq "^${appName}-[0-9]+\.[0-9]+\.[0-9]+"; then
    pinned=true
  else
    pinned=false
  fi

  jq -nc \
    --arg appName "$appName" \
    --arg cluster "$cluster" \
    --arg environment "$environment" \
    --arg releaseName "$releaseName" \
    --arg targetRevision "$targetRevision" \
    --arg chartRepo "$chart_repo" \
    --arg chartPath "${chart_prefix}${appName}" \
    --arg valuesFile "clusters/${cluster}/apps/${appName}.yaml" \
    --arg namespace "${environment}${ns_suffix}" \
    --argjson pinned "$pinned" \
    '{appName:$appName,cluster:$cluster,environment:$environment,releaseName:$releaseName,targetRevision:$targetRevision,chartRepo:$chartRepo,chartPath:$chartPath,valuesFile:$valuesFile,namespace:$namespace,pinned:$pinned}'
}

{
  for i in $(seq 0 $((n - 1))); do emit "$i"; done
} | jq -sc '.'
